### ISSUE TITLE
Image broken in landscape mode

### ISSUE THREAD

**Issue by 3lvis** [hyperoslo/AsyncMediaSlider#5]
- Open app
- Rotate

![ios simulator screen shot 23 apr 2015 13 56 22](https://cloud.githubusercontent.com/assets/1088217/7296530/cb90b8d2-e9c0-11e4-86fa-2bdb4793b0e0.png)

**Comment by jacob-andersson** [comment]
https://github.com/hyperoslo/AsyncMediaSlider/pull/6

**Comment by 3lvis** [comment]
![ios simulator screen shot 23 apr 2015 15 13 22](https://cloud.githubusercontent.com/assets/1088217/7297834/c980af1a-e9cb-11e4-8b0b-668c3bd12631.png)
![ios simulator screen shot 23 apr 2015 15 13 20](https://cloud.githubusercontent.com/assets/1088217/7297833/c97de42e-e9cb-11e4-8f44-02d05cc58e9e.png)
